services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }

    sonata.block.service.rss:
        class: Sonata\BlockBundle\Block\RssBlockService
        arguments:
            - sonata.block.service.rss
            - "@templating"
        tags:
            - { name: sonata.block }
