services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }

    sonata.block.gallery:
        class: AppBundle\Service\Block\GalleryBlockService
        arguments:
            - ~
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

    app.block.main_content:
        class: AppBundle\Service\Block\MainContentBlockService
        arguments:
            - ~
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            -
             { name: sonata.block }

    app.block.footer:
            class: AppBundle\Service\Block\FooterBlockService
            arguments:
                - ~
                - "@templating"
                - "@doctrine.orm.entity_manager"
            tags:
                - { name: sonata.block }

    app.block.faq:
          class: AppBundle\Service\Block\FaqBlockService
          arguments:
              - ~
              - "@templating"
              - "@doctrine.orm.entity_manager"
          tags:
              - { name: sonata.block }

    app.block.contact:
        class: AppBundle\Service\Block\ContactBlockService
        arguments:
            - ~
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

    app.block.categories_content:
        class: AppBundle\Service\Block\CategoriesContentBlockService
        arguments:
            - ~
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

    app.block.header:
        class: AppBundle\Service\Block\HeaderBlockService
        arguments:
            - ~
            - "@templating"
        tags:
          - { name: sonata.block }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }

    app.sonata.block.menu:
        class: AppBundle\Service\Block\SiteMenuBlockService
        arguments:
            - "My menu"
            - "@templating"
            - "@knp_menu.menu_provider"
            - "%main_menu%"
            - "%sidebar_menu%"
        tags:
            - { name: sonata.block }

    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@sonata.page.cms.page", "@doctrine.orm.entity_manager", "@request_stack"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: %main_menu% }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: %sidebar_menu% }

    app.route_listener:
        class: AppBundle\EventListener\RouteListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest  }

    app.admin.category_collection:
        class: AppBundle\Admin\CategoryCollectionAdmin
        arguments: [~, AppBundle\Entity\CategoryCollection, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CategoryCollection }

    app.admin.faq:
        class: AppBundle\Admin\FaqAdmin
        arguments: [~, AppBundle\Entity\Faq, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Faq }

    app.admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Contact }
