services:
    app.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, AppBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }

    sonata.block.gallery:
        class: AppBundle\Service\Block\GalleryBlockService
        arguments:
            - ~
            - "@templating"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: sonata.block }

    app.block.header:
        class: AppBundle\Service\Block\HeaderBlockService
        arguments:
            - ~
            - "@templating"
        tags:
          - { name: sonata.block }

    app.admin.product:
        class: AppBundle\Admin\ProductAdmin
        arguments: [~, AppBundle\Entity\Product, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Product }

    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }
